### ISSUE TITLE
`gca` terminology?

### ISSUE THREAD

**Issue by arxanas** [quark-zju/gitrevset#3]
The `gca` function returns the merge-base/nearest common ancestor for a pair of commits. I think the name is misleading for most Git users. Correct me if I'm mistaken.

In the lattice interpretation of the commit graph, we say that *a* < *b* if *a* is a descendant of *b*. A merge-base for *a* and *b* is a **least** commit *x* with *a* < *x* and *b* < *x*, which is to say that it's a nearest or lowest ancestor.

On the other hand, in the segmented changelog representation, the nodes are topologically ordered starting from 1 and monotonically increasing, so the interpretation is reversed. If *a* is a descendant of *b*, then it follows that, numerically, *b* < *a*.  In that sense, a merge-base for *a* and *b* is a **greatest**-valued node in the DAG. I'm assuming that this is why the `gca` function is called that.

I think most Git users will either be unfamiliar with both of these systems, or will be familiar with the lattice interpretation. I would recommend renaming the function to something which is agnostic to notions of < for the DAG structure, like `mb/mergebase` or `nca` (nearest common ancestor).

**Comment by quark-zju** [comment]
Perhaps it can be renamed to "ancestor", which is what hg uses exactly. How does that sound?

The terminology choices are currently optimized for people who are familiar with hg revset language. hg does not use "mergebase" so I'm hesitant to use it here. That said, with some customization API you can define it on your own.

The name "gca" does have a few references:

- bitkeeper has `bk gca` command: https://www.bitkeeper.org/man/gca.html
- `hg help revisions` explains "ancestor" as "A greatest common ancestor of the changesets". https://www.mercurial-scm.org/repo/hg/help/revisions
- hg uses `gca` in source code: https://www.mercurial-scm.org/repo/hg/file/e2e72daac90b/mercurial/cext/revlog.c#l2237

Note hg revision numbers are also sorted topologically starting from 0, similar to what you saw in segmented changelog.

Is there documentation for the "lattice interpretation of the commit graph"? I don't remember seeing it in git man pages, and when I searched "lattice" in https://github.com/git/git I got empty result.

**Comment by arxanas** [comment]
I spoke mistakenly. The Git commit graph structure doesn't form a lattice anyways. I was only thinking of these kinds of lattice diagrams, for which you could use something similar to represent a commit graph; conventionally, the least nodes are at the bottom:

![2d_modular_lattice svg](https://user-images.githubusercontent.com/454057/126582210-3d389437-ad95-496b-bda2-8ec610a5e663.png)

Interestingly, the documentation for [`git merge-base`](https://git-scm.com/docs/git-merge-base) only says the "best" common ancestor, and avoids saying exactly what "best" means in topological terms. This might be because of the `--fork-point` mode, which uses the reflog to sometimes choose a different ancestor.

You make a compelling case for `gca`, so I leave it to your discretion. One convenient point over `ancestor` is simply that it's easier to type :)
